# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 435)
        MainWindow.setStyleSheet("background-color : \"#212121\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 36, 421, 291))
        self.textEdit.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid white;\n"
"border-bottom-right-radius: 6px;\n"
"border-top-right-radius: 6px;")
        self.textEdit.setObjectName("textEdit")
        self.enterTag_le = QtWidgets.QLineEdit(self.centralwidget)
        self.enterTag_le.setGeometry(QtCore.QRect(10, 336, 271, 21))
        self.enterTag_le.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid white;\n"
"border-bottom-right-radius : 5px;\n"
"border-top-right-radius : 5px;\n"
"border-bottom-left-radius : 5px;")
        self.enterTag_le.setObjectName("enterTag_le")
        self.newNote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.newNote_btn.setGeometry(QtCore.QRect(440, 360, 75, 23))
        self.newNote_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-bottom-right-radius : 5px;\n"
"border-top-left-radius : 5px;")
        self.newNote_btn.setObjectName("newNote_btn")
        self.deleteNote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteNote_btn.setGeometry(QtCore.QRect(528, 360, 75, 23))
        self.deleteNote_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-top-right-radius : 5px;\n"
"border-bottom-left-radius : 5px;")
        self.deleteNote_btn.setObjectName("deleteNote_btn")
        self.addTag_btn = QtWidgets.QPushButton(self.centralwidget)
        self.addTag_btn.setGeometry(QtCore.QRect(285, 335, 71, 23))
        self.addTag_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-bottom-right-radius : 5px;\n"
"border-top-left-radius : 5px;")
        self.addTag_btn.setObjectName("addTag_btn")
        self.note_label = QtWidgets.QLabel(self.centralwidget)
        self.note_label.setGeometry(QtCore.QRect(440, 10, 81, 13))
        self.note_label.setStyleSheet("color : white")
        self.note_label.setObjectName("note_label")
        self.tags_list = QtWidgets.QListWidget(self.centralwidget)
        self.tags_list.setGeometry(QtCore.QRect(440, 240, 161, 111))
        self.tags_list.setStyleSheet("background-color : \"#303030\";\n"
"border : 1px solid white;\n"
"border-radius : 6px;\n"
"color : white;")
        self.tags_list.setObjectName("tags_list")
        self.notes_list = QtWidgets.QListWidget(self.centralwidget)
        self.notes_list.setGeometry(QtCore.QRect(440, 30, 161, 181))
        self.notes_list.setStyleSheet("background-color : \"#303030\";\n"
"border : 1px solid white;\n"
"border-radius : 6px;\n"
"color : white;")
        self.notes_list.setObjectName("notes_list")
        self.tags_label = QtWidgets.QLabel(self.centralwidget)
        self.tags_label.setGeometry(QtCore.QRect(440, 220, 47, 13))
        self.tags_label.setStyleSheet("color : white;")
        self.tags_label.setObjectName("tags_label")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(359, 335, 75, 23))
        self.search_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-bottom-right-radius : 5px;\n"
"border-top-left-radius : 5px;")
        self.search_btn.setObjectName("search_btn")
        self.name_le = QtWidgets.QLineEdit(self.centralwidget)
        self.name_le.setGeometry(QtCore.QRect(10, 10, 421, 20))
        self.name_le.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid white;\n"
"border-bottom-right-radius : 5px;\n"
"border-top-right-radius : 5px;\n"
"border-top-left-radius : 5px;\n"
"")
        self.name_le.setObjectName("name_le")
        self.unpinNote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unpinNote_btn.setGeometry(QtCore.QRect(527, 390, 75, 23))
        self.unpinNote_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-top-left-radius : 5px;\n"
"border-bottom-right-radius : 5px")
        self.unpinNote_btn.setObjectName("unpinNote_btn")
        self.addNote_btn = QtWidgets.QPushButton(self.centralwidget)
        self.addNote_btn.setGeometry(QtCore.QRect(440, 390, 75, 23))
        self.addNote_btn.setStyleSheet("background-color : \"#303030\";\n"
"color : white;\n"
"border : 1px solid \"#e8e8e8\";\n"
"border-top-right-radius : 5px;\n"
"border-bottom-left-radius : 5px;")
        self.addNote_btn.setObjectName("addNote_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Notes"))
        self.enterTag_le.setText(_translate("MainWindow", "Enter tag..."))
        self.newNote_btn.setText(_translate("MainWindow", "New Note"))
        self.deleteNote_btn.setText(_translate("MainWindow", "Delete Note"))
        self.addTag_btn.setText(_translate("MainWindow", "Add Tag"))
        self.note_label.setText(_translate("MainWindow", "Notes"))
        self.tags_label.setText(_translate("MainWindow", "Tags"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        self.name_le.setText(_translate("MainWindow", "Name..."))
        self.unpinNote_btn.setText(_translate("MainWindow", "Unpin Note"))
        self.addNote_btn.setText(_translate("MainWindow", "Add Note"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
